import { RowDataPacket } from "mysql2"

export interface Equipments extends RowDataPacket {
    id?: number; // optional field, auto generated by db
    serial_number: string; // No duplicates
    state: string;
    equip_name: string;
    category: string;
    cost: number;

    status: string;
    functionality: string;
    under_warrenty: boolean;
    cluster: number;
    installation_date: string;
}

