import { RowDataPacket } from "mysql2"

export interface Equipments extends RowDataPacket {
    id?: number; // optional field, auto generated by db
    state: string;
    district: string;
    facility: string; 
    category: string;
    equip_name: string;
    cost: number;
    serial_number: string;
    department: string;
    manufacturer: string;
    model: string;
    price: string;
    installation_date: string;
    under_warrenty: boolean;
    warrenty_date: string;
    functionality: string;
    status: string;
    return_date: string;
    borrow_date: string;
    cluster: number;
}
